name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        haxe-version: [4.2.5]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Setup Haxe environment
        uses: krdlab/setup-haxe@23a78f711bc4a623db38eac90d351ff0027f0116
        with:
          haxe-version: ${{ matrix.haxe-version }}

      - name: Install testing framework
        run: haxelib install buddy

      - name: Install datetime for gigasecond
        run: haxelib install datetime

      - name: Compile test
        run: bin/build.sh
